# Generated by Django 2.2.6 on 2019-10-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigparking',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='current_places',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='free_places',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkomat',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
