# Generated by Django 2.2.6 on 2019-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191005_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='work_time',
            field=models.CharField(default='8:00-19:00', max_length=255),
        ),
    ]
