# Generated by Django 2.2.6 on 2019-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191005_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='cost',
            field=models.FloatField(default=100),
        ),
    ]
