# Generated by Django 2.2.6 on 2019-10-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191005_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='x0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='x1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='x2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='x3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='y0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='y1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='y2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='y3',
            field=models.FloatField(default=0),
        ),
    ]
