# Generated by Django 2.2.6 on 2019-10-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191005_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='parking_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_place', to='main.Parking'),
        ),
    ]
