# Generated by Django 2.2.6 on 2019-10-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191005_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='free_places',
        ),
    ]
