# Generated by Django 2.2.6 on 2019-10-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_parking_free_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkomat',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parkomat',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
