# Generated by Django 2.2.6 on 2019-10-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191006_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='x0',
            new_name='x4',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='y0',
            new_name='y4',
        ),
    ]
