# Generated by Django 2.2.6 on 2019-10-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191006_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='busy_places',
            field=models.IntegerField(default=0),
        ),
    ]
