# Generated by Django 2.2.6 on 2019-10-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_parking_busy_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='time_count',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
